name: build

on:
  push:

jobs:
  Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          echo Testing 1...
          exit 0
      - name: Test 2
        run: |
          cargo fmt
          exit 0

