name: build

on:
  push:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          echo Testing 1...
          cargo --version
          exit 0
      - name: Test 2
        run: |
          cargo fmt
          exit 1

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          echo Testing 1...
          cargo --version
          exit 0
      - name: Test 2
        run: |
          cargo fmt
          exit 1

